import base64
import secrets
from .base import Cipher


class OneTimePadCipher(Cipher):
    name = "One-Time Pad (OTP)"

    @staticmethod
    def generate_key_for_text(text: str) -> str:
        raw = secrets.token_bytes(len(text.encode("utf-8")))
        return base64.b64encode(raw).decode("ascii")

    @staticmethod
    def _decode_key(key: str) -> bytes:
        try:
            return base64.b64decode(key, validate=True)
        except Exception as exc:
            raise ValueError("OTP key must be Base64 generated by this application.") from exc

    def encrypt(self, plaintext: str, key: str) -> str:
        data = plaintext.encode("utf-8")
        key_bytes = self._decode_key(key)
        if len(key_bytes) != len(data):
            raise ValueError("OTP key must be exactly the same byte length as plaintext.")
        cipher = bytes(a ^ b for a, b in zip(data, key_bytes))
        return base64.b64encode(cipher).decode("ascii")

    def decrypt(self, ciphertext: str, key: str) -> str:
        try:
            data = base64.b64decode(ciphertext, validate=True)
        except Exception as exc:
            raise ValueError("OTP ciphertext must be valid Base64.") from exc
        key_bytes = self._decode_key(key)
        if len(key_bytes) != len(data):
            raise ValueError("OTP key must be exactly the same byte length as ciphertext bytes.")
        plain = bytes(a ^ b for a, b in zip(data, key_bytes))
        return plain.decode("utf-8")
